import BazarPrintPage from '@/components/bazar/bazar-data-print'
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: "Print Bazar Data",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <BazarPrintPage/>
  )
}

export default page
