import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const roboto = Poppins({
  weight:["400", "500"]

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        roboto.className
      )}
    >
      <body className="min-h-full flex flex-col bg-slate-300">{children}</body>
    </html>
  );
}
