import PrintableChallanPage from '@/components/challan/printable-challan'
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: "Challan",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
    <div>
      <PrintableChallanPage/>
    </div>
    </>
  )
}

export default page
